<#
.SYNOPSIS
  Start the production-profile backend + PostgreSQL for local/ops use.

.DESCRIPTION
  Minimal stack: postgres + backend (prod Spring profile).
  - Creates .env.production at the repo root if missing (gitignored secrets).
  - Uses docker-compose.prod.yml + docker-compose.prod.backend-local.yml
  - Does not start frontend, reverse-proxy, or database-backup.

.PARAMETER EnvFile
  Path to the production env file (default: <repo>/.env.production).

.PARAMETER Rebuild
  Force image rebuild.

.PARAMETER Detached
  Start containers and return to the prompt without streaming logs.
  Default behavior streams backend logs in this terminal (Ctrl+C leaves logs; containers keep running).
#>
[CmdletBinding()]
param(
    [string]$EnvFile,
    [switch]$Rebuild,
    [switch]$Detached
)

$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
if ([string]::IsNullOrWhiteSpace($EnvFile)) {
    $EnvFile = Join-Path $repoRoot ".env.production"
}

function New-RandomSecret([int]$ByteLength) {
    $bytes = New-Object byte[] $ByteLength
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $rng.GetBytes($bytes)
    }
    finally {
        $rng.Dispose()
    }
    return [Convert]::ToBase64String($bytes)
}

function Ensure-ProductionEnvFile([string]$Path) {
    if (Test-Path -LiteralPath $Path) {
        Write-Host "Using existing env file: $Path"
        return
    }

    Write-Host "Creating $Path with generated secrets (file is gitignored)..."
    $dbPassword = New-RandomSecret -ByteLength 32
    $jwtSecret = New-RandomSecret -ByteLength 48

    $content = @"
# Local production-profile backend env — generated by scripts/Start-ProductionBackend.ps1
# Do not commit this file. Rotate secrets for any real deployment.

SPRING_PROFILES_ACTIVE=prod
SERVER_PORT=8080
BACKEND_HOST_PORT=8080

POSTGRES_DB=bwc_campaign
DB_USERNAME=bwc_app
DB_PASSWORD=$dbPassword
DB_URL=jdbc:postgresql://postgres:5432/bwc_campaign
DB_POOL_MAX_SIZE=20
DB_POOL_MIN_IDLE=2
DB_CONNECTION_TIMEOUT_MS=30000
DB_VALIDATION_TIMEOUT_MS=5000

JWT_SECRET=$jwtSecret
JWT_ISSUER=bayer-westphalian-campaign-platform
JWT_ACCESS_TOKEN_MINUTES=15
JWT_REFRESH_TOKEN_DAYS=7

# Must be explicit HTTPS non-localhost origins (ProductionCorsOrigins).
# Browser calls from Vite localhost will be CORS-blocked; use curl/Postman or a matching HTTPS front origin.
CORS_ALLOWED_ORIGINS=https://campaign.bayer-westphalian.example

# Local overlay sets HTTPS_REQUIRED false for direct :8080 access.
HTTPS_REQUIRED_LOCAL=false
HTTPS_HSTS_ENABLED_LOCAL=false
HTTPS_REQUIRED=true
HTTPS_HSTS_ENABLED=true

OPENAPI_ENABLED=false
SWAGGER_UI_ENABLED=false
SHUTDOWN_TIMEOUT=30s

ADMIN_BOOTSTRAP_ENABLED=false
ADMIN_BOOTSTRAP_EMAIL=
ADMIN_BOOTSTRAP_PASSWORD=
ADMIN_BOOTSTRAP_FULL_NAME=Production Administrator

PROVIDER_REAL_SENDING_ENABLED=false
EMAIL_PROVIDER_MODE=disabled
SMS_PROVIDER_MODE=disabled
FILE_STORAGE_MODE=filesystem
FILE_STORAGE_MAX_BYTES=10485760

CONTACT_MONTHLY_LIMIT=3
CONTACT_RETRY_LIMIT=3
UNINTERESTED_EXCLUSION_DAYS=90
REMINDER_PROCESSING_CRON=0 */15 * * * *
REMINDER_PROCESSING_ZONE=UTC

LOG_LEVEL_ROOT=INFO
LOG_LEVEL_APPLICATION=INFO
LOG_LEVEL_SPRING=WARN
LOG_LEVEL_SCHEDULER=INFO
LOG_MAX_SIZE=10m
LOG_MAX_FILES=5

# Required by full prod compose reverse-proxy; unused when only postgres+backend start.
# Prefer absolute paths; run scripts/Ensure-LocalProductionTls.ps1 after first generate.
TLS_CERTIFICATE_PATH=./docker/tls/fullchain.pem
TLS_PRIVATE_KEY_PATH=./docker/tls/privkey.pem
HTTP_PORT=80
HTTPS_PORT=443
"@

    Set-Content -LiteralPath $Path -Value $content -Encoding UTF8
    Write-Host "Wrote $Path"
    Write-Host "For full stack (proxy/HTTPS), run: .\scripts\Ensure-LocalProductionTls.ps1"
}

function Assert-DockerAvailable {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        throw "Docker is not installed or not on PATH."
    }
    docker info 1>$null 2>$null
    if ($LASTEXITCODE -ne 0) {
        throw "Docker daemon is not running. Start Docker Desktop, then retry."
    }
}

Assert-DockerAvailable
Ensure-ProductionEnvFile -Path $EnvFile

$composeArgs = @(
    "compose",
    "--env-file", $EnvFile,
    "-f", (Join-Path $repoRoot "docker-compose.prod.yml"),
    "-f", (Join-Path $repoRoot "docker-compose.prod.backend-local.yml")
)

Write-Host "Validating production compose (postgres + backend)..."
& docker @composeArgs config 1>$null
if ($LASTEXITCODE -ne 0) {
    throw "docker compose config failed. Check $EnvFile required values."
}

$upArgs = @("up", "-d")
if ($Rebuild) {
    $upArgs += "--build"
}
else {
    $upArgs += "--build"
}
$upArgs += @("postgres", "backend")

Write-Host "Starting production-profile postgres + backend..."
Push-Location $repoRoot
try {
    & docker @composeArgs @upArgs
    if ($LASTEXITCODE -ne 0) {
        throw "docker compose up failed with exit code $LASTEXITCODE"
    }

    Write-Host ""
    Write-Host "Services:"
    & docker @composeArgs ps postgres backend

    Write-Host ""
    Write-Host "Backend (prod profile) should become healthy on http://localhost:8080"
    Write-Host "Health:  curl http://localhost:8080/actuator/health"
    Write-Host "Stop:    docker compose --env-file `"$EnvFile`" -f docker-compose.prod.yml -f docker-compose.prod.backend-local.yml stop postgres backend"

    if ($Detached) {
        Write-Host "Detached mode: not streaming logs. To follow later:"
        Write-Host "  docker compose --env-file `"$EnvFile`" -f docker-compose.prod.yml -f docker-compose.prod.backend-local.yml logs -f backend"
        return
    }

    Write-Host ""
    Write-Host "Streaming backend logs (Ctrl+C stops log view only; containers keep running)..."
    Write-Host ""
    # --tail=200 shows recent boot lines, then follows new output.
    & docker @composeArgs logs --tail=200 -f backend
}
finally {
    Pop-Location
}
